FROM postgres:17-alpine

COPY migrations /migrations
COPY infra/postgres/migrate.sh /usr/local/bin/nexora-migrate

RUN chmod 0555 /usr/local/bin/nexora-migrate     && chmod -R a=rX /migrations

ENTRYPOINT ["/usr/local/bin/nexora-migrate"]
